### ISSUE TITLE
Some completed example

### ISSUE THREAD

**Issue by chwu-rwth** [sitn/pytree#28]
Hi, I have followed the instructions but nothing seems to work. 
```  
# path to cpotree exectuable
  cpotree_executable: extract_profile
# Available point clouds. NOTE: pointclouds CRS must be the same as the APP, reprojection is not implemented!
  pointclouds:
    swissSURFACE3D: ./PCtree/Output/pointclouds/Potree/metadata.json
# point cloud to use in profile
  default_point_cloud: swissSURFACE3D 
```

I am unsure how is the "path to CPotree executable" and "default_point_cloud" is defined. 
Would be great if there is some example. 

Docker-compose is as below:
```
version: "3.8"

services:
  api:
    image: sitn/pytree:1.0.5
    environment:
      DEPLOY_ENV: ${DEPLOY_ENV:-DEV}
    restart: unless-stopped
    command: /app/start_server.sh
    volumes:
      - ./PCtree/Output/pointclouds/Potree:/app/data
      - ./pytree.yml:/app/pytree.yml
    ports:
      - "${PORT:-6001}:5000"
```
